services:
  redis:
    image: redis:latest
    container_name: avg-price-redis
    ports:
      - "6379:6379"

  service-api:
    build:
      context: ./service-api
    container_name: avg-price-service-api
    ports:
      - "3000:3000"
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis

  service-binance:
    build:
      context: ./service-binance
    container_name: avg-price-service-binance
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis

  service-kraken:
    build:
      context: ./service-kraken
    container_name: avg-price-service-kraken
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis

  service-huobi:
    build:
      context: ./service-huobi
    container_name: avg-price-service-huobi
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
